# Generated by `make cask`. Edit the generator, not this file: the version and
# the checksum have to match a release that is actually published, and a hand
# edit is how those two drift apart.
cask "mymicrotunnel" do
  version "1.5.8"
  sha256 "dce0d83c0c798042d65d100ce1ecfa880c85e8a7ed4b637812ce175b60880317"

  url "https://downloads.maragato.ca/releases/MyMicroTunnel-#{version}.pkg"
  name "MyMicroTunnel"
  desc "Publishes a local port at a hostname you own, over WireGuard to AWS"
  homepage "https://mymicrotunnel.maragato.ca/"

  # The same feed the app's own updater reads, so brew and the app never
  # disagree about what the current version is.
  livecheck do
    url "https://downloads.maragato.ca/appcast.xml"
    strategy :sparkle
  end

  auto_updates true
  depends_on macos: :ventura

  pkg "MyMicroTunnel-#{version}.pkg"

  uninstall launchctl: "ca.maragato.mymicrotunnel.supervisor",
            quit:      "ca.maragato.mymicrotunnel-menubar",
            pkgutil:   "ca.maragato.mymicrotunnel",
            delete:    [
              "/etc/sudoers.d/mymicrotunnel",
              "/Library/LaunchDaemons/ca.maragato.mymicrotunnel.supervisor.plist",
              "/Library/PrivilegedHelperTools/ca.maragato.mymicrotunnel.helper",
              "/usr/local/bin/mymicrotunnel",
              "/usr/local/lib/mymicrotunnel",
            ]

  # Deliberately not removed by `uninstall`: the profiles name deployments that
  # exist in an AWS account and cost money, and /etc/wireguard holds the
  # private key those deployments trust. Taking either away on a plain
  # uninstall would leave a stack nothing on this Mac can reach, still running.
  #
  # `brew uninstall --zap` is the explicit ask for that, and even then the AWS
  # side has to go first: run `mymicrotunnel uninstall` while the profiles are
  # still here.
  zap delete: "/etc/wireguard",
      trash:  [
        "~/Library/Application Support/MyMicroTunnel",
        "~/Library/Caches/ca.maragato.mymicrotunnel-menubar",
        "~/Library/Preferences/ca.maragato.mymicrotunnel-menubar.plist",
      ]

  caveats <<~EOS
    MyMicroTunnel deploys AWS resources into your own account, which cost
    roughly USD 26/month while a gateway is running. Open the menu bar icon
    and choose Setup to deploy one.

    Before uninstalling, run `mymicrotunnel uninstall` so the AWS side goes
    with it. Removing the app alone leaves the stack running and billing.
  EOS
end
